//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sereflikochisar.altinkaynak {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://data.altinkaynak.com/", ConfigurationName="altinkaynak.DataServiceSoap")]
    public interface DataServiceSoap {
        
        // CODEGEN: Generating message contract since message GetCurrencyRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://data.altinkaynak.com/GetCurrency", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        sereflikochisar.altinkaynak.GetCurrencyResponse GetCurrency(sereflikochisar.altinkaynak.GetCurrencyRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://data.altinkaynak.com/GetCurrency", ReplyAction="*")]
        System.Threading.Tasks.Task<sereflikochisar.altinkaynak.GetCurrencyResponse> GetCurrencyAsync(sereflikochisar.altinkaynak.GetCurrencyRequest request);
        
        // CODEGEN: Generating message contract since message GetGoldRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://data.altinkaynak.com/GetGold", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        sereflikochisar.altinkaynak.GetGoldResponse GetGold(sereflikochisar.altinkaynak.GetGoldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://data.altinkaynak.com/GetGold", ReplyAction="*")]
        System.Threading.Tasks.Task<sereflikochisar.altinkaynak.GetGoldResponse> GetGoldAsync(sereflikochisar.altinkaynak.GetGoldRequest request);
        
        // CODEGEN: Generating message contract since message GetMainRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://data.altinkaynak.com/GetMain", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        sereflikochisar.altinkaynak.GetMainResponse GetMain(sereflikochisar.altinkaynak.GetMainRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://data.altinkaynak.com/GetMain", ReplyAction="*")]
        System.Threading.Tasks.Task<sereflikochisar.altinkaynak.GetMainResponse> GetMainAsync(sereflikochisar.altinkaynak.GetMainRequest request);
        
        // CODEGEN: Generating message contract since message GetParityRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://data.altinkaynak.com/GetParity", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        sereflikochisar.altinkaynak.GetParityResponse GetParity(sereflikochisar.altinkaynak.GetParityRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://data.altinkaynak.com/GetParity", ReplyAction="*")]
        System.Threading.Tasks.Task<sereflikochisar.altinkaynak.GetParityResponse> GetParityAsync(sereflikochisar.altinkaynak.GetParityRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://data.altinkaynak.com/")]
    public partial class AuthHeader : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string usernameField;
        
        private string passwordField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
                this.RaisePropertyChanged("Username");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("Password");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
                this.RaisePropertyChanged("AnyAttr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetCurrency", WrapperNamespace="http://data.altinkaynak.com/", IsWrapped=true)]
    public partial class GetCurrencyRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://data.altinkaynak.com/")]
        public sereflikochisar.altinkaynak.AuthHeader AuthHeader;
        
        public GetCurrencyRequest() {
        }
        
        public GetCurrencyRequest(sereflikochisar.altinkaynak.AuthHeader AuthHeader) {
            this.AuthHeader = AuthHeader;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetCurrencyResponse", WrapperNamespace="http://data.altinkaynak.com/", IsWrapped=true)]
    public partial class GetCurrencyResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://data.altinkaynak.com/", Order=0)]
        public string GetCurrencyResult;
        
        public GetCurrencyResponse() {
        }
        
        public GetCurrencyResponse(string GetCurrencyResult) {
            this.GetCurrencyResult = GetCurrencyResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetGold", WrapperNamespace="http://data.altinkaynak.com/", IsWrapped=true)]
    public partial class GetGoldRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://data.altinkaynak.com/")]
        public sereflikochisar.altinkaynak.AuthHeader AuthHeader;
        
        public GetGoldRequest() {
        }
        
        public GetGoldRequest(sereflikochisar.altinkaynak.AuthHeader AuthHeader) {
            this.AuthHeader = AuthHeader;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetGoldResponse", WrapperNamespace="http://data.altinkaynak.com/", IsWrapped=true)]
    public partial class GetGoldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://data.altinkaynak.com/", Order=0)]
        public string GetGoldResult;
        
        public GetGoldResponse() {
        }
        
        public GetGoldResponse(string GetGoldResult) {
            this.GetGoldResult = GetGoldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetMain", WrapperNamespace="http://data.altinkaynak.com/", IsWrapped=true)]
    public partial class GetMainRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://data.altinkaynak.com/")]
        public sereflikochisar.altinkaynak.AuthHeader AuthHeader;
        
        public GetMainRequest() {
        }
        
        public GetMainRequest(sereflikochisar.altinkaynak.AuthHeader AuthHeader) {
            this.AuthHeader = AuthHeader;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetMainResponse", WrapperNamespace="http://data.altinkaynak.com/", IsWrapped=true)]
    public partial class GetMainResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://data.altinkaynak.com/", Order=0)]
        public string GetMainResult;
        
        public GetMainResponse() {
        }
        
        public GetMainResponse(string GetMainResult) {
            this.GetMainResult = GetMainResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetParity", WrapperNamespace="http://data.altinkaynak.com/", IsWrapped=true)]
    public partial class GetParityRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://data.altinkaynak.com/")]
        public sereflikochisar.altinkaynak.AuthHeader AuthHeader;
        
        public GetParityRequest() {
        }
        
        public GetParityRequest(sereflikochisar.altinkaynak.AuthHeader AuthHeader) {
            this.AuthHeader = AuthHeader;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetParityResponse", WrapperNamespace="http://data.altinkaynak.com/", IsWrapped=true)]
    public partial class GetParityResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://data.altinkaynak.com/", Order=0)]
        public string GetParityResult;
        
        public GetParityResponse() {
        }
        
        public GetParityResponse(string GetParityResult) {
            this.GetParityResult = GetParityResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface DataServiceSoapChannel : sereflikochisar.altinkaynak.DataServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DataServiceSoapClient : System.ServiceModel.ClientBase<sereflikochisar.altinkaynak.DataServiceSoap>, sereflikochisar.altinkaynak.DataServiceSoap {
        
        public DataServiceSoapClient() {
        }
        
        public DataServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DataServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DataServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DataServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        sereflikochisar.altinkaynak.GetCurrencyResponse sereflikochisar.altinkaynak.DataServiceSoap.GetCurrency(sereflikochisar.altinkaynak.GetCurrencyRequest request) {
            return base.Channel.GetCurrency(request);
        }
        
        public string GetCurrency(sereflikochisar.altinkaynak.AuthHeader AuthHeader) {
            sereflikochisar.altinkaynak.GetCurrencyRequest inValue = new sereflikochisar.altinkaynak.GetCurrencyRequest();
            inValue.AuthHeader = AuthHeader;
            sereflikochisar.altinkaynak.GetCurrencyResponse retVal = ((sereflikochisar.altinkaynak.DataServiceSoap)(this)).GetCurrency(inValue);
            return retVal.GetCurrencyResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<sereflikochisar.altinkaynak.GetCurrencyResponse> sereflikochisar.altinkaynak.DataServiceSoap.GetCurrencyAsync(sereflikochisar.altinkaynak.GetCurrencyRequest request) {
            return base.Channel.GetCurrencyAsync(request);
        }
        
        public System.Threading.Tasks.Task<sereflikochisar.altinkaynak.GetCurrencyResponse> GetCurrencyAsync(sereflikochisar.altinkaynak.AuthHeader AuthHeader) {
            sereflikochisar.altinkaynak.GetCurrencyRequest inValue = new sereflikochisar.altinkaynak.GetCurrencyRequest();
            inValue.AuthHeader = AuthHeader;
            return ((sereflikochisar.altinkaynak.DataServiceSoap)(this)).GetCurrencyAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        sereflikochisar.altinkaynak.GetGoldResponse sereflikochisar.altinkaynak.DataServiceSoap.GetGold(sereflikochisar.altinkaynak.GetGoldRequest request) {
            return base.Channel.GetGold(request);
        }
        
        public string GetGold(sereflikochisar.altinkaynak.AuthHeader AuthHeader) {
            sereflikochisar.altinkaynak.GetGoldRequest inValue = new sereflikochisar.altinkaynak.GetGoldRequest();
            inValue.AuthHeader = AuthHeader;
            sereflikochisar.altinkaynak.GetGoldResponse retVal = ((sereflikochisar.altinkaynak.DataServiceSoap)(this)).GetGold(inValue);
            return retVal.GetGoldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<sereflikochisar.altinkaynak.GetGoldResponse> sereflikochisar.altinkaynak.DataServiceSoap.GetGoldAsync(sereflikochisar.altinkaynak.GetGoldRequest request) {
            return base.Channel.GetGoldAsync(request);
        }
        
        public System.Threading.Tasks.Task<sereflikochisar.altinkaynak.GetGoldResponse> GetGoldAsync(sereflikochisar.altinkaynak.AuthHeader AuthHeader) {
            sereflikochisar.altinkaynak.GetGoldRequest inValue = new sereflikochisar.altinkaynak.GetGoldRequest();
            inValue.AuthHeader = AuthHeader;
            return ((sereflikochisar.altinkaynak.DataServiceSoap)(this)).GetGoldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        sereflikochisar.altinkaynak.GetMainResponse sereflikochisar.altinkaynak.DataServiceSoap.GetMain(sereflikochisar.altinkaynak.GetMainRequest request) {
            return base.Channel.GetMain(request);
        }
        
        public string GetMain(sereflikochisar.altinkaynak.AuthHeader AuthHeader) {
            sereflikochisar.altinkaynak.GetMainRequest inValue = new sereflikochisar.altinkaynak.GetMainRequest();
            inValue.AuthHeader = AuthHeader;
            sereflikochisar.altinkaynak.GetMainResponse retVal = ((sereflikochisar.altinkaynak.DataServiceSoap)(this)).GetMain(inValue);
            return retVal.GetMainResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<sereflikochisar.altinkaynak.GetMainResponse> sereflikochisar.altinkaynak.DataServiceSoap.GetMainAsync(sereflikochisar.altinkaynak.GetMainRequest request) {
            return base.Channel.GetMainAsync(request);
        }
        
        public System.Threading.Tasks.Task<sereflikochisar.altinkaynak.GetMainResponse> GetMainAsync(sereflikochisar.altinkaynak.AuthHeader AuthHeader) {
            sereflikochisar.altinkaynak.GetMainRequest inValue = new sereflikochisar.altinkaynak.GetMainRequest();
            inValue.AuthHeader = AuthHeader;
            return ((sereflikochisar.altinkaynak.DataServiceSoap)(this)).GetMainAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        sereflikochisar.altinkaynak.GetParityResponse sereflikochisar.altinkaynak.DataServiceSoap.GetParity(sereflikochisar.altinkaynak.GetParityRequest request) {
            return base.Channel.GetParity(request);
        }
        
        public string GetParity(sereflikochisar.altinkaynak.AuthHeader AuthHeader) {
            sereflikochisar.altinkaynak.GetParityRequest inValue = new sereflikochisar.altinkaynak.GetParityRequest();
            inValue.AuthHeader = AuthHeader;
            sereflikochisar.altinkaynak.GetParityResponse retVal = ((sereflikochisar.altinkaynak.DataServiceSoap)(this)).GetParity(inValue);
            return retVal.GetParityResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<sereflikochisar.altinkaynak.GetParityResponse> sereflikochisar.altinkaynak.DataServiceSoap.GetParityAsync(sereflikochisar.altinkaynak.GetParityRequest request) {
            return base.Channel.GetParityAsync(request);
        }
        
        public System.Threading.Tasks.Task<sereflikochisar.altinkaynak.GetParityResponse> GetParityAsync(sereflikochisar.altinkaynak.AuthHeader AuthHeader) {
            sereflikochisar.altinkaynak.GetParityRequest inValue = new sereflikochisar.altinkaynak.GetParityRequest();
            inValue.AuthHeader = AuthHeader;
            return ((sereflikochisar.altinkaynak.DataServiceSoap)(this)).GetParityAsync(inValue);
        }
    }
}
